import os

TOKEN = os.environ['BK_PRICE_TRACKER_BOT_TOKEN']

DATABASE_NAME = 'testdb'
DATABASE_USER_NAME = 'leonidpsql'
DATABASE_USER_PASSWORD = 'password'
DATABASE_HOST = 'localhost'
DATABASE_PORT = '5432'

PRODUCTS_TABLE_NAME = 'products'
PRODUCTS_TABLE_BARCODE_COLUMN_NAME = 'barcode'
PRODUCTS_TABLE_SKU_COLUMN_NAME = 'sku'
PRODUCTS_TABLE_URL_COLUMN_NAME = 'url'

USERS_TABLE_NAME = 'users'

LIST_PRODUCTS_EXCEL_FILE_NAME = 'products.xlsx'
